### ISSUE TITLE
sys.argv part missing for 018_Running_Python

### ISSUE THREAD

**Issue by qwu-570** [UCL-EO/geog0111#11]
Before 'Formative assessment', notes ended without introducing how to feed sys.argv into helloWorld.py

**Comment by profLewis** [comment]
Well, my idea was to given them all of the information they needed, but to leave them to put those pieces together in the formative assessment. Otherwise, there is no real purpose to that assessment.

So ... Ive put it in ... but also changed the assessment to something a little more complex.
