### ISSUE TITLE
Qingling edits ? broken notebook 021

### ISSUE THREAD

**Issue by profLewis** [UCL-EO/geog0111#14]
Unreadable Notebook: /nfs/cfs/home3/Uucfa6/ucfalew/geog0111/notebooks/021_Streams.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...')****

I think you (qingling) have edited the file but broken the formatting -- can you roll it back and fix?

**Comment by qwu-570** [comment]
seems to be working fine on my end. did you fix it already?

**Comment by profLewis** [comment]
No ... did you download the latest one with git?

Professor Philip Lewis, UCL

**Comment by profLewis** [comment]
seems fine now
