### ISSUE TITLE
Some small typos in 050_Models.ipynb

### ISSUE THREAD

**Issue by wanxinyang** [UCL-EO/geog0111#20]
In the notebook 050_Models.ipynb, some typos might cause confusion and would be better to update:

Prerequisties section: 

- np**/**mgrid  ->  np**.**mgrid
- "You should **by know** be familiar"  -> "You should **now** be familiar"

Models section:

- the last line above the first code cell: "This has two parameters p[0] and **p[0]**"  ->  the second p[0] might be **p[1]**

Discrepancy and optimisation section:

- "The best approach **with** depend on circumstances"  ->  "The best approach **will** depend on circumstances"

**Comment by wanxinyang** [comment]
In notebook 051_Phenology_model.ipynb, there is also a small typo:

In the help document of the function `simple_dbl_sigmoid_function(sp,p, t)`, 
“”**p2** is 2 parameters: width and centre“  ->  "**sp** is 2 parameters: width and centre“.

**Comment by profLewis** [comment]
done.
